// <auto-generated />
using System;
using BeautyAcademyApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeautyAcademyApi.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BeautyAcademyApi.Models.Aluno", b =>
                {
                    b.Property<int>("Matricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CargoId")
                        .HasColumnType("int");

                    b.Property<long>("Celular")
                        .HasMaxLength(11)
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Matricula");

                    b.HasIndex("CargoId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("BeautyAcademyApi.Models.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("BeautyAcademyApi.Models.Curso", b =>
                {
                    b.Property<int>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("IdCurso");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("BeautyAcademyApi.Models.MatriculaCurso", b =>
                {
                    b.Property<int>("IdMatriculaCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.Property<int>("Matricula")
                        .HasColumnType("int");

                    b.HasKey("IdMatriculaCurso");

                    b.HasIndex("IdCurso");

                    b.HasIndex("Matricula");

                    b.ToTable("MatriculadeCursos");
                });

            modelBuilder.Entity("BeautyAcademyApi.Models.Aluno", b =>
                {
                    b.HasOne("BeautyAcademyApi.Models.Cargo", "Cargo")
                        .WithMany("Alunos")
                        .HasForeignKey("CargoId");

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("BeautyAcademyApi.Models.MatriculaCurso", b =>
                {
                    b.HasOne("BeautyAcademyApi.Models.Curso", "Curso")
                        .WithMany("MatriculaCursos")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeautyAcademyApi.Models.Aluno", "Aluno")
                        .WithMany("MatriculaCursos")
                        .HasForeignKey("Matricula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("BeautyAcademyApi.Models.Aluno", b =>
                {
                    b.Navigation("MatriculaCursos");
                });

            modelBuilder.Entity("BeautyAcademyApi.Models.Cargo", b =>
                {
                    b.Navigation("Alunos");
                });

            modelBuilder.Entity("BeautyAcademyApi.Models.Curso", b =>
                {
                    b.Navigation("MatriculaCursos");
                });
#pragma warning restore 612, 618
        }
    }
}
